### ISSUE TITLE
The problem of some files in v0.1.0 and v0.4.0

### ISSUE THREAD

**Issue by nolsherry** [colepeters/gemma#6]
Hello @colepeters,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
I found in version `0.1.0` that there has no `gemma.min.css` file on both [github](https://github.com/colepeters/gemma/tree/0.1.0) and [npm](https://www.npmjs.com/package/gemma).
And in version `0.4.0`, the file `gemma.min.css` didn't minified.
Could you help me update these files? Thanks!

cdnjs/cdnjs#9034

**Comment by colepeters** [comment]
Hi @nolsherry, thanks for getting in touch, and for your interest in Gemma. Versions of Gemma before 1.x were pre-production versions where I was mostly just working out my ideas about the project. I don’t have any plans for maintaining or supporting the versions you’ve mentioned (they are effectively deprecated, and I honestly would not recommend that anyone use them).

**Comment by nolsherry** [comment]
@colepeters, thanks for your response, we will ignore the two versions.
